modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="before_and_after_ragnarok"
version="1.0.0"
displayName="Before_and_After_Ragnarok"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="matti, MCreator"

[[dependencies.before_and_after_ragnarok]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




